name: Deploy buy runner
on:
  push:
    branches: [ "master", "develop","main" ]
  pull_request:
    types: [ opened, synchronize, reopened ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout target repo
        uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Checkout tests
        uses: actions/checkout@v3
        with:
          repository: 'AleksandrIsa4/person-web-service-docker'
          ref: ${{ github.event.pull_request.head.ref }}
          path: tests
      - name: Check and Build application
        run: |
          cp -rf ./tests/checkstyle.xml ./checkstyle.xml
          cp -rf ./tests/suppressions.xml ./suppressions.xml
          mvn install -P check --no-transfer-progress
          docker-compose build
  deploy:
    needs: build
    runs-on: self-hosted
    if: github.ref == 'refs/heads/asd2'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run command on remote server
        run: |
          cd ${{ secrets.PROJECT_FOLDER }};
          git fetch;
          git checkout develop;
          git pull;
          mvn clean package;
          docker compose down;
          docker compose build;
          docker compose up -d;