name: Deploy buy runner

on:
  pull_request:
    types: [ opened, synchronize, reopened ]

  deploy:
    needs: build
    runs-on: self-hosted
    if: github.ref == 'refs/heads/develop2'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run command on remote server
        run: |
          cd ${{ secrets.PROJECT_FOLDER }};
          git fetch;
          git checkout develop;
          git pull;
          mvn clean package;
          docker compose down;
          docker compose build;
          docker compose up -d;