name: pull-unner

on:
  pull_request:
    branches:
      - asd2
  push:
    branches:
      - asd2

  deploy:
    needs: build
    #if: github.ref == 'refs/heads/asd2'
    runs-on: ubuntu-latest
    #if: github.event.pull_request.merged == true  || ${{github.ref == 'refs/heads/asd2'}} ${{github.ref == 'refs/heads/develop2(3)'}}
    #if: ${{github.ref == 'refs/pull/asd2/merge'}}
    #&& github.event.pull_request.merged == true
    steps:
      - run: echo  ${{github.ref}}
      - run: echo  ${{github.ref == 'refs/heads/asd2'}}
      - run: echo  ${{github.ref == 'refs/heads/develop5'}}
      - run: echo  ${{github.event.pull_request.merged}}
      - name: executing remote ssh commands to deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          port: ${{ secrets.SERVER_PORT }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script_stop: true
          script: |
            cd /srv/person-web-service-docker
            git fetch
            git checkout asd2
            git pull
            mvn clean package
            docker stop person-gateway-container
            docker rm person-gateway-container
            docker-compose up -d