name: pull-unner

on:
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout target repo
        uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Checkout tests
        uses: actions/checkout@v3
        with:
          repository: 'AleksandrIsa4/person-web-service-docker'
          ref: ${{ github.event.pull_request.head.ref }}
          path: tests
      - name: Check and Build application
        run: |
          cp -rf ./tests/checkstyle.xml ./checkstyle.xml
          cp -rf ./tests/suppressions.xml ./suppressions.xml
          mvn install -P check --no-transfer-progress
          docker-compose build
  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/develop2(3)'
    #if: github.event.pull_request.merged == true
    #if: ${{ github.ref == 'refs/heads/develop2(3)' }}
    #&& github.event.pull_request.merged == true

    steps:
    - name: executing remote ssh commands to deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        port: ${{ secrets.SERVER_PORT }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        script_stop: true
        script:
          cd ${{ secrets.PROJECT_FOLDER }};
          git fetch;
          git checkout develop2(3);
          git pull;
          mvn clean package;
          docker stop ${{ secrets.DOCKER_NAME }};
          docker rm ${{ secrets.DOCKER_NAME }};
          docker-compose up -d;